name: Generate Repo

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # needed for switching branches

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Generate Repo
      run: dotnet run --repo

    - name: Save generated file
      run: |
        mkdir _generated
        cp repo.json _generated/

    - name: Configure git identity
      run: |
        git config user.name "Automated"
        git config user.email "auto@auto.test"

    - name: Switch to 'generated' branch (create if needed)
      run: |
        if git show-ref --quiet refs/heads/generated; then
          git switch generated
        else
          git switch --orphan generated
          git rm -rf .
        fi

    - name: Restore generated file
      run: cp _generated/repo.json .

    - name: Stage file
      run: git add repo.json

    - name: Commit changes
      run: |
        git diff --quiet && echo "No changes to commit" || git commit -m "Auto repo.json update"

    - name: Push to generated branch
      run: git push origin HEAD:generated
