name: Generate Repo

on:
  push:
    branches: [ "main", "build" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: generated-repo-json

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: main

      - name: Checkout build branch
        uses: actions/checkout@v3
        with:
          ref: build
          fetch-depth: 0
          path: build

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        working-directory: build
        run: dotnet restore

      - name: Generate Repo
        working-directory: build
        run: dotnet run --repo

      - name: List generated files
        run: find build -type f

      - name: Upload generated repo.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-repo-json
          path: build/repo.json

  update-generated-branch:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout generated branch
        uses: actions/checkout@v3
        with:
          ref: generated
          fetch-depth: 0

      - name: Create generated branch if it doesn't exist
        if: failure()
        run: |
          git checkout --orphan generated
          git rm -rf .
          git commit --allow-empty -m "Initial generated branch commit"
          git push origin generated

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: generated-repo-json
          path: .

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit repo.json
        run: |
          git add repo.json
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update repo.json"

      - name: Push to generated branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} generated
