name: Generate Repo

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Generate Repo
      run: dotnet run --repo
    - name: check for changes
      run: git status
    - name: set username
      run: git config user.name "Automated"
    - name: set email
      run: git config user.email "auto@auto.test"
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto repo.json"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
