name: Generate Repo

on:
  push:
    branches: [ "main", "build" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout build branch
        uses: actions/checkout@v4
        with:
          ref: build
          path: build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Combine main + build into temp folder
        run: |
          mkdir combined
          cp -r main/. combined/
          cp -r build/. combined/

      - name: Restore and build
        working-directory: combined
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Run generator
        working-directory: combined
        run: |
          dotnet run --configuration Release

      - name: Copy generated repo.json
        run: |
          mkdir generated
          cp combined/repo.json generated/repo.json

      - name: Commit repo.json to generated branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git fetch origin generated || true
          git checkout -B generated origin/generated || git checkout --orphan generated

          rm -rf *
          cp generated/repo.json repo.json

          git add repo.json
          git commit -m "Update generated repo.json" || echo "No changes to commit"
          git push origin generated --force
