name: Generate Repo

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Generate Repo
      run: dotnet run --repo

    - name: List files for debugging
      run: |
        echo "::group::Generated files"
        find . -type f
        echo "::endgroup::"

    - name: Upload generated repo.json artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-repo-json
        path: repo.json

    - name: Configure git
      run: |
        git config user.name "Automated"
        git config user.email "auto@auto.test"

    - name: Reset repo to clean state
      run: |
        git reset --hard
        git clean -fd

    - name: Switch to 'generated' branch (create if needed)
      run: |
        if git ls-remote --exit-code --heads origin generated; then
          git checkout generated
        else
          git checkout --orphan generated
          git rm -rf .
        fi

    - name: Download generated repo.json artifact
      uses: actions/download-artifact@v4
      with:
        name: generated-repo-json
        path: .

    - name: Commit changes
      run: |
        git add repo.json
        git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto repo.json update"

    - name: Push to generated branch
      run: git push origin HEAD:generated
