name: Generate Repo

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required to switch/create branches

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Generate Repo
      run: dotnet run --repo

    - name: Save generated file(s)
      run: |
        mkdir _generated
        cp repo.json _generated/repo.json

    - name: Configure git
      run: |
        git config user.name "Automated"
        git config user.email "auto@auto.test"

    - name: Reset repo to clean state
      run: |
        git reset --hard
        git clean -fd

    - name: Switch to 'generated' branch (create if needed)
      run: |
        if git ls-remote --exit-code --heads origin generated; then
          git checkout generated
        else
          git checkout --orphan generated
          git rm -rf .
        fi

    - name: Restore generated file(s)
      run: cp _generated/repo.json .

    - name: Commit changes
      run: |
        git add repo.json
        git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto repo.json update"

    - name: Push to generated branch
      run: git push origin HEAD:generated
